Web_App/inflexion/gallery/urls.py
from django.urls import path

from . import views
app_name = 'gallery'
urlpatterns = [
    path('', views.index, name='index'),
    path('log_in/', views.log_in, name="log_in"),
    path('register/', views.register, name='register'),
    path('log_out/', views.log_out, name='log_out'),
    path('userpage/', views.adminpage, name='userpage'),
    path('upload_image/', views.upload_image, name="upload_image")
]

Web_App/inflexion/inflexion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Web_App/inflexion/gallery/models.py
from django.db import models

# Create your models here.


class UserReg(models.Model):
    name = models.CharField(max_length=32)
    email = models.CharField(max_length=32)
    password = models.CharField(max_length=16)


class Images(models.Model):
    image = models.ImageField(upload_to='images')
    title = models.CharField(max_length=32)

Web_App/inflexion/gallery/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from .models import Images


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user


# class ImageCreation(forms.ModelForm):
# 	class Meta:
# 		model = Images
# 		fields = ("title", 'image')
#
# 	def save(self, commit=True):
# 		image = self.cleaned_data['image']
# 		image_details = super(ImageCreation, self).save(commit=False)
# 		if commit:
# 			image_details.save()
#
# 		return image_details

class LoginForm(AuthenticationForm):

	class Meta:
		model = User
		fields = ("email", "password1")

Web_App/inflexion/gallery/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .decorators import unauthenticated, allowed_user
from .forms import NewUserForm
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

from .models import Images


def index(request):
    return render(request, "gallery/index.html")


@allowed_user(roles_allowed=['admin'])
def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("gallery:index")

    form = NewUserForm()
    return render(request, "gallery/user.html",
                  {"register_form": form})


@unauthenticated
def log_in(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                if user.groups.all()[0].name == 'admin':
                    return render(request, 'gallery/index.html',
                                  {"user": user, "name": "admin"})
                else:
                    return render(request, 'gallery/index.html',
                                  {"user": user,"name": "user"})
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request, "gallery/log_in.html", context={"login_form": form})


@login_required
def log_out(request):
    logout(request)
    return redirect('gallery:index')


@login_required
@allowed_user(roles_allowed=['admin'])
def adminpage(request):
    images = Images.objects.all()
    return render(request, "gallery/image.html",
                  {
                      "images": images
                  })

@login_required
def upload_image(request):
    if request.method == "POST":
        image_details = Images()
        image_details.image = request.FILES['image']

        image_details.title = request.POST.get('title')
        image_details.save()
        messages.success(request, "Image has been uploaded successfully")
        return render(request, "gallery/upload.html",
                      {"images": image_details})
    return render(request, "gallery/upload.html")

Web_App/inflexion/gallery/templates/gallery/admin.html
{% extends 'gallery/layout.html' %}

{% block content %}
    <center>

        {% if user.is_authenticated %}
            <p>Hello, <b>{{ user.username }}</b></p>
            <p> You have been logged in through <b>{{ user.email }}</b></p>
            <a href="{% url 'gallery:log_out' %}"><button>Log Out </button></a>
            <a href="{% url 'gallery:register' %}"><button>Register</button></a>
            <a href="{% url 'gallery:userpage' %}"><button>Uploaded Images</button></a>

        {% endif %}
    </center>
{% endblock %}

Web_App/inflexion/gallery/templates/gallery/image.html
{% extends 'gallery/layout.html' %}

{% block content %}
<a href="{% url 'gallery:log_out' %}"><button>Log Out </button></a>
<p>Gallery</p>
{% for i in images %}
    <img src="{{ i.image.url }}">
{% endfor %}
{% endblock %}

Web_App/inflexion/gallery/templates/gallery/index.html
{% extends 'gallery/layout.html' %}

{% block content %}
    <center>

        {% if user.is_authenticated %}
            <p>Hello, <b>{{ user.username }}</b></p>
            <p> You have been logged in through <b>{{ user.email }}</b></p>
            <a href="{% url 'gallery:log_out' %}"><button>Log Out </button></a>

            {% if name == "admin" %}
                <a href="{% url 'gallery:register' %}"><button>Register</button></a>
                <a href="{% url 'gallery:userpage' %}"><button>Uploaded Images</button></a>
            {% else %}
            <a href="{% url 'gallery:upload' %}"><button>Uploaded Images</button></a>
            {% endif %}
        {% else %}
            <p>No you are not logged in</p>
            <a href="{% url 'gallery:log_in' %}"><button>Login</button></a>


        {% endif %}
    </center>
{% endblock %}

Web_App/inflexion/gallery/templates/gallery/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inflexion</title>
</head>
<body>
        <p align="center">Welcome to Inflexion Point Technologies BD LTD</p>
        {% block content %}

        {% endblock %}
</body>
</html>

Web_App/inflexion/gallery/templates/gallery/log_in.html
{% extends 'gallery/layout.html' %}

{% block content %}
    <center>
        <p>Login</p>
        <form method="post"action="{% url 'gallery:log_in' %}">
            {% csrf_token %}
            {{ login_form.as_p }}
            <input type="submit"value="Login"name="user">
        </form>
    </center>
{% endblock %}

Web_App/inflexion/gallery/templates/gallery/upload.html
{% extends 'gallery/layout.html' %}

{% block content %}
{% if user.is_authenticated %}
<center>
    <p>Add Image</p>
    <form method="POST" action="{% url 'gallery:upload_image' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="image" >
        <input type="text" placeholder="title" name="title" >
        <button type="submit">Post</button>
    </form>
    <br><br>
        <a href="{% url 'gallery:log_out' %}"><button>Log Out </button></a>
</center>
{% endif %}
{% endblock %}

Web_App/inflexion/gallery/templates/gallery/user.html
{% extends 'gallery/layout.html' %}

{% block content %}
    <center>
        <p>Creating User</p>
        <form method="post"action="{% url 'gallery:register' %}">
            {% csrf_token %}
            {{ register_form.as_p }}
            <input type="submit"value="save"name="user">
        </form>
    </center>
{% endblock %}